# -*- coding: utf-8 -*-
"""4_step_machine_learning.ipynb6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMfsgzlir_WCJZcze1nWKNWTcI8W5jB2
"""

import pandas as pd
import numpy as np
import sklearn

df = pd.read_csv('https://raw.githubusercontent.com/ageron/handson-ml2/refs/heads/master/datasets/housing/housing.csv')

from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

x_train = train_set.drop("median_house_value", axis=1)
y = train_set["median_house_value"].copy()

x_num = x_train.drop("ocean_proximity", axis=1)

from sklearn.base import BaseEstimator, TransformerMixin

rooms_ix, bedrooms_ix, population_ix, households_ix = 3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True):
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        rooms_per_household = X[:, rooms_ix] / X[:, households_ix]
        population_per_household = X[:, population_ix] / X[:, households_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household, bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

num_pipline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('attribs_adder', CombinedAttributesAdder()),
    ('std_scaler', StandardScaler())
])
num_pipline.fit_transform(x_num)

from sklearn.compose import ColumnTransformer

num_attribs = list(x_num)
cat_attribs = ['ocean_proximity']

full_pipeline = ColumnTransformer([
    ('num', num_pipline, num_attribs),
    ('cat', OneHotEncoder(), cat_attribs)
])

x_prepared = full_pipeline.fit_transform(x_train)

from sklearn.linear_model import LinearRegression

lr_model = LinearRegression()
lr_model.fit(x_prepared, y)

test_data = x_train.sample(10)
test_data

test_label = y.loc[test_data.index]
test_label

test_data_prepared = full_pipeline.transform(test_data)
predicted_labels = lr_model.predict(test_data_prepared)
predicted_labels

pd.DataFrame({'Predicted': predicted_labels, 'Actual': test_label})